### ISSUE TITLE
基于机器学习的密码强度分类

### ISSUE THREAD

**Issue by 1352871** [jivoi/awesome-ml-for-cybersecurity#3]
基于机器学习的密码强度分类 这个链接失效～需要这份资源 希望分享  谢谢

**Comment by jivoi** [comment]
ok, thx

**Comment by GGchencan** [comment]
在校大学生，在做密码学大作业，基于机器学习的密码强度分类 ，需要这份资源， 希望您能分享 谢谢

**Comment by GGchencan** [comment]
可以发我邮箱ggchen@mail.ustc.edu.cn吗？感激不尽
