### ISSUE TITLE
Inaccessible links

### ISSUE THREAD

**Issue by JLJTECH** [jivoi/awesome-ml-for-cybersecurity#4]
On the ML for cyber security page: https://github.com/jivoi/awesome-ml-for-cybersecurity

The following links from http://fsecurify.com are inaccessible: 
[Using Neural Networks to generate human readable passwords](http://fsecurify.com/using-neural-networks-to-generate-human-readable-passwords/)
[Machine Learning based Password Strength Classification](http://fsecurify.com/machine-learning-based-password-strength-checking/)
[Using Machine Learning to Detect Malicious URLs](http://fsecurify.com/using-machine-learning-detect-malicious-urls/)
[fWaf – Machine learning driven Web Application Firewall](http://fsecurify.com/fwaf-machine-learning-driven-web-application-firewall/)

**Comment by ankitkul** [comment]
Can I go ahead and fix it with the links from the wayback machine (http://web.archive.org/). I did the same fix for fsecurify on https://github.com/hangtwenty/dive-into-machine-learning

**Comment by ankitkul** [comment]
Just fixed the issue. Do let me know in case of any concerns. Thanks.
