### ISSUE TITLE
Dataset linked twice?

### ISSUE THREAD

**Issue by Scinawa** [jivoi/awesome-ml-for-cybersecurity#5]
Hi,
Marco Ramilli's dataset is linked twice: once as it's blog post, and then as his github repo.

-> Malware Training Sets: A machine learning dataset for everyone
KDD Cup 1999 Data
Web Attack Payloads
WAF Malicious Queries Data Sets
-> Malware Training Data Sets

**Comment by jivoi** [comment]
thx, fixed it =)
