### ISSUE TITLE
ML Cyber Sec

### ISSUE THREAD

**Issue by phenyojratsie** [jivoi/awesome-ml-for-cybersecurity#54]

**Comment by X-Lambert** [comment]
您好，您的邮件我已收到，我会尽快查收

**Comment by mk3709** [comment]
is there any contribution that can be made

**Comment by X-Lambert** [comment]
您好，您的邮件我已收到，我会尽快查收

**Comment by mk3709** [comment]
Can we do it in other lang too read.me so that everyone one major could
read it
